MARKET_DATA = [
    {
        "ticker": "NVDA",
        "name": "NVIDIA",
        "sector": "Technology",
        "industry": "Semiconductors",
        "market_cap": 2290,
        "current_price": 934.7,
        "day_change": 18.6,
        "day_change_percent": 2.03,
        "analyst_target_price": 1010.0,
        "price_change_1m": 12.4,
        "price_change_3m": 31.5,
        "earnings_revision": 8.7,
        "revenue_growth": 41.0,
        "gross_margin_trend": 4.8,
        "valuation_zscore": 1.9,
        "short_interest": 1.2,
        "borrow_fee": 0.4,
        "news_sentiment": 0.76,
        "event_risk": 0.82,
    },
    {
        "ticker": "AMD",
        "name": "AMD",
        "sector": "Technology",
        "industry": "Semiconductors",
        "market_cap": 284,
        "current_price": 176.2,
        "day_change": 2.4,
        "day_change_percent": 1.38,
        "analyst_target_price": 190.0,
        "price_change_1m": 6.1,
        "price_change_3m": 14.2,
        "earnings_revision": 3.5,
        "revenue_growth": 18.2,
        "gross_margin_trend": 1.8,
        "valuation_zscore": 1.3,
        "short_interest": 3.0,
        "borrow_fee": 0.8,
        "news_sentiment": 0.42,
        "event_risk": 0.61,
    },
    {
        "ticker": "PLUG",
        "name": "Plug Power",
        "sector": "Industrials",
        "industry": "Clean Energy Equipment",
        "market_cap": 2.1,
        "current_price": 3.4,
        "day_change": -0.22,
        "day_change_percent": -6.08,
        "analyst_target_price": 2.8,
        "price_change_1m": -18.4,
        "price_change_3m": -27.1,
        "earnings_revision": -12.6,
        "revenue_growth": -8.5,
        "gross_margin_trend": -9.7,
        "valuation_zscore": 1.5,
        "short_interest": 24.1,
        "borrow_fee": 11.2,
        "news_sentiment": -0.51,
        "event_risk": 0.39,
    },
    {
        "ticker": "TSLA",
        "name": "Tesla",
        "sector": "Consumer Discretionary",
        "industry": "Automobiles",
        "market_cap": 550,
        "current_price": 171.8,
        "day_change": -4.1,
        "day_change_percent": -2.33,
        "analyst_target_price": 162.0,
        "price_change_1m": -9.8,
        "price_change_3m": -16.0,
        "earnings_revision": -6.2,
        "revenue_growth": 1.2,
        "gross_margin_trend": -5.1,
        "valuation_zscore": 2.4,
        "short_interest": 3.1,
        "borrow_fee": 0.5,
        "news_sentiment": -0.22,
        "event_risk": 0.93,
    },
    {
        "ticker": "XOM",
        "name": "Exxon Mobil",
        "sector": "Energy",
        "industry": "Integrated Oil & Gas",
        "market_cap": 490,
        "current_price": 118.6,
        "day_change": 0.9,
        "day_change_percent": 0.76,
        "analyst_target_price": 124.0,
        "price_change_1m": 4.1,
        "price_change_3m": 9.6,
        "earnings_revision": 2.2,
        "revenue_growth": 6.4,
        "gross_margin_trend": 1.1,
        "valuation_zscore": -0.2,
        "short_interest": 1.0,
        "borrow_fee": 0.3,
        "news_sentiment": 0.21,
        "event_risk": 0.54,
    },
    {
        "ticker": "CVX",
        "name": "Chevron",
        "sector": "Energy",
        "industry": "Integrated Oil & Gas",
        "market_cap": 282,
        "current_price": 156.1,
        "day_change": 1.1,
        "day_change_percent": 0.71,
        "analyst_target_price": 167.0,
        "price_change_1m": 2.5,
        "price_change_3m": 6.1,
        "earnings_revision": 1.4,
        "revenue_growth": 4.2,
        "gross_margin_trend": 0.8,
        "valuation_zscore": -0.4,
        "short_interest": 0.8,
        "borrow_fee": 0.2,
        "news_sentiment": 0.14,
        "event_risk": 0.43,
    },
    {
        "ticker": "COST",
        "name": "Costco",
        "sector": "Consumer Staples",
        "industry": "Retail",
        "market_cap": 330,
        "current_price": 742.3,
        "day_change": 5.8,
        "day_change_percent": 0.79,
        "analyst_target_price": 760.0,
        "price_change_1m": 5.0,
        "price_change_3m": 8.8,
        "earnings_revision": 2.9,
        "revenue_growth": 8.4,
        "gross_margin_trend": 0.9,
        "valuation_zscore": 1.7,
        "short_interest": 0.9,
        "borrow_fee": 0.2,
        "news_sentiment": 0.31,
        "event_risk": 0.35,
    },
    {
        "ticker": "WBA",
        "name": "Walgreens Boots Alliance",
        "sector": "Consumer Staples",
        "industry": "Retail",
        "market_cap": 15,
        "current_price": 17.9,
        "day_change": -0.41,
        "day_change_percent": -2.24,
        "analyst_target_price": 15.5,
        "price_change_1m": -11.3,
        "price_change_3m": -21.4,
        "earnings_revision": -7.4,
        "revenue_growth": -2.3,
        "gross_margin_trend": -3.9,
        "valuation_zscore": -0.7,
        "short_interest": 6.3,
        "borrow_fee": 1.0,
        "news_sentiment": -0.38,
        "event_risk": 0.47,
    },
    {
        "ticker": "JPM",
        "name": "JPMorgan Chase",
        "sector": "Financials",
        "industry": "Banks",
        "market_cap": 545,
        "current_price": 198.4,
        "day_change": 1.7,
        "day_change_percent": 0.86,
        "analyst_target_price": 210.0,
        "price_change_1m": 3.8,
        "price_change_3m": 10.3,
        "earnings_revision": 1.8,
        "revenue_growth": 7.2,
        "gross_margin_trend": 0.5,
        "valuation_zscore": 0.3,
        "short_interest": 1.1,
        "borrow_fee": 0.2,
        "news_sentiment": 0.25,
        "event_risk": 0.48,
    },
    {
        "ticker": "AAL",
        "name": "American Airlines",
        "sector": "Industrials",
        "industry": "Airlines",
        "market_cap": 8.7,
        "current_price": 13.6,
        "day_change": -0.18,
        "day_change_percent": -1.31,
        "analyst_target_price": 12.4,
        "price_change_1m": -6.8,
        "price_change_3m": -13.2,
        "earnings_revision": -4.5,
        "revenue_growth": 2.8,
        "gross_margin_trend": -2.4,
        "valuation_zscore": 0.6,
        "short_interest": 10.8,
        "borrow_fee": 3.5,
        "news_sentiment": -0.12,
        "event_risk": 0.57,
    },
]
